export function createAuthPageStyles() {
  return {
    page: {
      background: '#080C14',
      minHeight: '100vh',
      color: '#F1EDE4',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontFamily: "'Space Mono', monospace",
      padding: '24px',
    },
    card: {
      background: 'rgba(255,255,255,0.02)',
      border: '1px solid rgba(255,255,255,0.07)',
      borderRadius: 14,
      padding: '40px 44px',
      width: '100%',
      maxWidth: 400,
      display: 'flex',
      flexDirection: 'column',
      gap: 24,
    },
    label: {
      display: 'block',
      fontSize: 10,
      letterSpacing: '0.15em',
      color: 'rgba(255,255,255,0.4)',
      textTransform: 'uppercase',
      marginBottom: 8,
    },
    input: {
      width: '100%',
      background: 'rgba(255,255,255,0.05)',
      border: '1px solid rgba(255,255,255,0.12)',
      borderRadius: 6,
      padding: '12px 14px',
      color: '#F1EDE4',
      fontFamily: "'Space Mono', monospace",
      fontSize: 13,
      outline: 'none',
      boxSizing: 'border-box',
    },
    btn: {
      background: 'transparent',
      border: '1.5px solid #6EE7D0',
      color: '#6EE7D0',
      fontFamily: "'Space Mono', monospace",
      fontSize: 12,
      fontWeight: 700,
      letterSpacing: '0.08em',
      padding: '14px',
      borderRadius: 8,
      cursor: 'pointer',
      textTransform: 'uppercase',
      width: '100%',
      transition: 'all 0.2s',
    },
    error: {
      fontSize: 12,
      color: '#FCA5A5',
      letterSpacing: '0.04em',
      padding: '10px 14px',
      background: 'rgba(252,165,165,0.08)',
      border: '1px solid rgba(252,165,165,0.25)',
      borderRadius: 6,
    },
    link: {
      color: '#6EE7D0',
      textDecoration: 'none',
      fontSize: 11,
    },
  }
}